spring.application.name=ticketmaster

# Relational Database Connection Engine (with shared memory flag)
spring.datasource.url=jdbc:h2:mem:ticketdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true

# User credentials (move to environment variables in production)
app.security.dev.username=dev_user
app.security.dev.password=dev123
app.security.admin.username=admin_user
app.security.admin.password=admin123